"""Write backend/constraints.txt: the exact versions of every package that requirements-dev.txt pulls in, read from the
environment the recorded results were produced in.

    python scripts/freeze_constraints.py            # rewrite constraints.txt from the current environment
    pip install -r requirements-dev.txt -c constraints.txt   # reproduce that environment in a clean clone

requirements*.txt keep lower bounds (what the code needs); this file records what was verified. It walks the dependency closure
of the requirement files through installed package metadata, so packages installed for other projects are not included. Local
version labels (torch's "+cu126" or "+cpu") are dropped, so the same file works with the CPU or CUDA wheel index.
"""
from __future__ import annotations

import re
import sys
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

HERE = Path(__file__).resolve().parents[1]


def top_level(path: Path) -> list[Requirement]:
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("-r "):
            out += top_level(path.parent / line[3:].strip())
        else:
            out.append(Requirement(line))
    return out


def closure(reqs: list[Requirement], missing: set[str]) -> dict[str, str]:
    env = default_environment()
    seen: dict[str, str] = {}
    todo = [(r, frozenset(r.extras)) for r in reqs]
    expanded: set[tuple[str, frozenset]] = set()
    while todo:
        req, extras = todo.pop()
        name = canonicalize_name(req.name)
        if (name, extras) in expanded:
            continue
        expanded.add((name, extras))
        try:
            dist = distribution(req.name)
        except PackageNotFoundError:
            missing.add(name)   # declared but absent from the verified environment: left unpinned and listed in the header
            continue
        seen[name] = re.sub(r"\+.*$", "", dist.version)
        for spec in dist.requires or []:
            sub = Requirement(spec)
            if sub.marker is None or any(sub.marker.evaluate(env | {"extra": e}) for e in (extras or {""})):
                todo.append((sub, frozenset(sub.extras)))
    return seen


if __name__ == "__main__":
    missing: set[str] = set()
    pins = closure(top_level(HERE / "requirements-dev.txt"), missing)
    head = [f"# Generated by scripts/freeze_constraints.py on Python {sys.version.split()[0]} ({sys.platform}); do not edit by hand.",
            "# The versions the recorded evaluation, load test and Kubernetes runs used. Use with: pip install -r requirements-dev.txt -c constraints.txt"]
    if missing:
        head.append(f"# Declared but not installed in that environment (left unpinned): {', '.join(sorted(missing))}")
    (HERE / "constraints.txt").write_text("\n".join(head + [f"{n}=={v}" for n, v in sorted(pins.items())]) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(pins)} pins to {HERE / 'constraints.txt'}")
