"""Turn the raw results of a suite into SUMMARY.md (tables only; every number is read from the run's summary.json).

    python loadtest/summarize.py 2026-10-06
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ORDER = ["no_llm", "no_llm_no_affect", "no_llm_warm", "mock_llm_warm", "llm", "llm_down", "llm_hang", "llm_hang_tuned"]


def f(x, nd=0):
    return "-" if x is None else (f"{x:.{nd}f}" if nd else f"{x:,.0f}")


def pct(x):
    return "-" if x is None else f"{x * 100:.1f}%"


def load(suite: Path):
    runs = {}
    for p in sorted(suite.glob("*/*/summary.json")):
        runs.setdefault(p.parent.parent.name, []).append((p.parent.name, json.loads(p.read_text(encoding="utf-8"))))
    return runs


def main(suite_name: str) -> None:
    suite = REPO / "loadtest" / "results" / suite_name
    runs = load(suite)
    env = json.loads((suite / "environment.json").read_text(encoding="utf-8"))
    out = [f"# Load test results: {suite_name}", "",
           f"Generated by `loadtest/summarize.py` from the raw files in this folder. Commit `{env.get('git_commit')}`"
           f"{' (working tree had uncommitted changes)' if env.get('git_dirty') else ''}, run on {env.get('date')}.", "",
           f"* Machine: {env.get('cpu_name') or env.get('cpu')} ({env.get('cpu_cores_physical')} cores / {env.get('cpu_threads')} threads), {env.get('ram_gb')} GB RAM, GPU {env.get('gpu')}",
           f"* Server: {env.get('api')}", f"* Models: {json.dumps(env.get('models'))}", f"* LLM settings: {json.dumps(env.get('llm_settings'))}", ""]
    for scen in sorted(runs, key=lambda s: ORDER.index(s) if s in ORDER else 99):
        items = sorted(runs[scen], key=lambda kv: (kv[1]["meta"].get("tracing", False), kv[1]["meta"]["users"]))
        first = items[0][1]
        out += [f"## {scen}: {first['meta']['description']}", "",
                f"cache mode `{first['cache_mode']}`, {first['pool']['in_domain']} in-domain + {first['pool']['out_of_domain']} out-of-domain complaints "
                f"({first['ood_share'] * 100:.0f}% out-of-domain), overrides `{json.dumps(first['meta']['overrides'])}`", "",
                "| run | users | secs | completed | OK req/s | P50 ms | P95 ms | P99 ms | max ms | errors | timeouts | evidence-only | abstained | API CPU cores (mean/max) | GPU % (mean) |",
                "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
        for name, s in items:
            r, lat, res = s["requests"], s["latency_ms_ok"], s.get("resources", {})
            n_ok = r["ok"] or 1
            oc = s.get("outcome", {})
            cpu, gpu = res.get("api_cpu_cores") or {}, res.get("gpu_util_pct") or {}
            small = " (n<100: P99 not meaningful)" if lat.get("n", 0) < 100 else ""
            out.append(f"| {name} | {s['meta']['users']} | {f(s['wall_seconds'])} | {r['completed']} | {f(s['throughput']['ok_per_s'], 2)} | {f(lat.get('p50'))} | "
                       f"{f(lat.get('p95'))} | {f(lat.get('p99'))}{'*' if small else ''} | {f(lat.get('max'))} | {pct(r['error_rate'])} | {pct(r['timeout_rate'])} | "
                       f"{pct(oc.get('degraded', 0) / n_ok if r['ok'] else None)} | {pct(oc.get('abstained', 0) / n_ok if r['ok'] else None)} | "
                       f"{f(cpu.get('mean'), 1)} / {f(cpu.get('max'), 1)} | {f(gpu.get('mean'))} |")
        if any(it[1]["latency_ms_ok"].get("n", 0) < 100 for it in items):
            out += ["", "\\* fewer than 100 successful requests: the P99 is effectively the maximum."]
        out += ["", "Latency columns are for successful (HTTP 200) requests; failed requests are counted in `errors` / `timeouts` (see `summary.json` -> `latency_ms_all` for latency including them). "
                    "`evidence-only` = answered 200 without LLM text (the degraded fallback), `abstained` = deliberately declined for weak evidence.", ""]
        kinds = {name: s["requests"]["by_kind"] for name, s in items if set(s["requests"]["by_kind"]) - {"ok"}}
        if kinds:
            out += ["Failures by kind: " + "; ".join(f"`{n}` {json.dumps(k)}" for n, k in kinds.items()), ""]
        out += ["Server-side mean time per stage (ms, from the API's own `latency_ms` in the responses; includes waiting inside the process):", "",
                "| run | preprocess | embed | classify | retrieve | generate | total | affect model (Prometheus) | LLM call (Prometheus) | circuit open at end |",
                "|---|---:|---:|---:|---:|---:|---:|---:|---:|---|"]
        for name, s in items:
            st, m = s["server_stage_ms_ok"], s["server_metrics"]
            g = lambda k: f((st.get(k) or {}).get("mean"), 1)  # noqa: E731
            llm = (m.get("llm_call") or {}).get("ollama", {})
            aff = (m.get("affect_model") or {}).get("all", {})
            out.append(f"| {name} | {g('preprocess')} | {g('embed')} | {g('classify')} | {g('retrieve')} | {g('generate')} | {g('total')} | "
                       f"{f(aff.get('mean_ms'), 1)} | {f(llm.get('mean_ms'), 1)} ({llm.get('count', 0)}) | {json.dumps(m.get('llm_circuit_open_at_end'))} |")
        out.append("")
        traced = [(n, s) for n, s in items if s.get("trace_spans")]
        for name, s in traced:
            ts = s["trace_spans"]
            out += [f"### Span durations from OpenTelemetry traces ({name}, {ts['traces']} traces)", "", "| span | count | mean ms | P95 ms |", "|---|---:|---:|---:|"]
            out += [f"| {k} | {v['count']} | {v['mean_ms']} | {v['p95_ms']} |" for k, v in list(ts["spans"].items())[:18]]
            out.append("")
    (suite / "SUMMARY.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {suite / 'SUMMARY.md'}")


if __name__ == "__main__":
    main(sys.argv[1])
